CREATE TABLE IF NOT EXISTS method (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT NOT NULL UNIQUE
);
INSERT OR IGNORE INTO method (name) VALUES ('GET'), ('POST'), ('PUT'), ('DELETE'), ('PATCH'), ('HEAD');

CREATE TABLE IF NOT EXISTS collection (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT NOT NULL UNIQUE,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	description TEXT
);
CREATE UNIQUE INDEX collection_name ON collection(name);

CREATE TABLE IF NOT EXISTS request (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	url TEXT NOT NULL,
	method_id INTEGER NOT NULL,
	collection_id INTEGER NOT NULL,	

	FOREIGN KEY(method_id) REFERENCES method(id),
	FOREIGN KEY(collection_id) REFERENCES collection(id)
);